site_name: Balises Sonores Ouistici
site_url: https://balises-sonores.github.io/

theme:
  name: readthedocs
  locale: fr
  logo: ouistici.png
  palette: 
    - primary: grey
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Site en mode sombre
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Site en mode lumineux

copyright: Balises Ouistici, un projet des Petit⋅e⋅s Débrouillard⋅e⋅s Aura

markdown_extensions:
  - attr_list
  - admonition
  - md_in_html
  - def_list
  # - pymdownx.details
  # - pymdownx.superfences

plugins:
  - search
  